#!/bin/sh

export HOME=/home/sciteit
cd $HOME/sciteit/r2
exec 2>&1
exec setuidgid sciteit /usr/local/bin/paster run run.ini r2/lib/utils/utils.py -c "from r2.lib.db import queries; queries.run_commentstree()"
