#!/bin/sh

export HOME=/home/sciteit
cd $HOME/sciteit/r2
exec 2>&1
exec setuidgid sciteit /usr/local/bin/paster run run.ini -c "from r2.lib.db import queries; queries.process_votes(queries.vote_link_q, limit=100)"
